// Generated file, do not edit. Source: scripts/src/gen-icons.ts (pnpm gen)
export const iconNames = [
  'house',
  'shopping-bag',
  'shopping-cart',
  'truck',
  'clipboard-list',
  'boxes',
  'wallet',
  'receipt',
  'send',
  'flower-2',
  'user-round',
  'chevron-left',
  'chevron-right',
  'search',
  'x',
  'plus',
  'minus',
  'trash-2',
  'log-out',
  'info',
  'store',
  'image',
  'check',
  'sliders-horizontal',
  'calendar',
  'chevron-down',
] as const
