// 阶段 3 页面的文案（06 章 S1–S9、X1–X11、H1–H3、F1–F9、M2）：copy.screen，和 copy.ts 同一个出处规则
export const screen = {
  // 页面、弹层标题和模块首页入口名：思源宋体子集从这里抽字（scripts/gen-font）
  title: {
    shop: '订货',
    cart: '购物车',
    storeOrders: '订单',
    checkout: '结算',
    orderDetail: '订单详情',
    storeAfters: '售后',
    applyAfter: '申请售后',
    statement: '对账',
    salesOrders: '销售订单',
    createOrder: '新建订单',
    editOrder: '修改订单',
    editAndConfirm: '修改并确认',
    confirmOrder: '确认订单',
    salesAfters: '客户售后',
    afterDetail: '售后详情',
    createAfter: '新建售后',
    processAfter: '处理售后',
    customers: '客户门店',
    createCustomer: '新建客户',
    editCustomer: '编辑客户',
    createStore: '新建门店',
    editStore: '编辑门店',
    inviteStore: '邀请下单',
    products: '产品管理',
    createProduct: '新建产品',
    editProduct: '编辑产品',
    categories: '管理分类',
    directory: '订货目录',
    shipList: '发货单',
    ship: '发货',
    arCustomers: '客户对账',
    arCustomer: '客户对账详情',
    registerReceipt: '登记收款',
    allocate: '核销预收',
    receipt: '收款详情',
    records: '收付款记录',
    methods: '收付款方式',
    pickOrder: '选择订单',
    pickProduct: '选择产品',
    pickMaterial: '选择花材',
    picked: '已选产品',
    todos: '待办',
  },
  tab: { cart: '购物车' },
  // 按钮：单据级操作码的按钮名（05 章第 1.5 节）和页面按钮
  action: {
    storeEdit: '修改订单',
    storeCancel: '取消订单',
    applyAfter: '申请售后',
    confirm: '确认订单',
    editAndConfirm: '修改并确认',
    edit: '修改订单',
    cancel: '取消订单',
    createAfter: '新建售后',
    ship: '确认发货',
    processAfter: '处理售后',
    closeAfter: '关闭售后',
    voidAfter: '作废售后',
    allocate: '核销预收',
    registerReceipt: '登记收款',
    voidReceipt: '作废收款',
    inviteStore: '邀请下单',
    unbindStoreWechat: '解绑微信',
    createOrder: '新建订单',
    createCustomer: '新建客户',
    createStore: '新建门店',
    editCustomer: '编辑客户',
    createProduct: '新建产品',
    manageCategories: '管理分类',
    addCategory: '新增分类',
    addProduct: '添加产品',
    addMaterial: '添加花材',
    toCheckout: '去结算',
    submitOrder: '提交订单',
    confirmEdit: '确认修改',
    saveEdit: '保存修改',
    submitAfter: '提交售后',
    confirmReceipt: '确认收款',
    confirmAllocate: '确认核销',
    fill: '填入',
    add: '添加',
    clear: '清空',
    viewAll: '查看全部',
    shipRecords: '发货记录',
    generateInvite: '生成邀请',
    shareInvite: '发送给门店',
    goMy: '去我的',
    confirmCancel: '确认取消',
    confirmClose: '确认关闭',
    confirmVoid: '确认作废',
    moveUp: '上移',
    delete: '删除',
  },
  // 详情、表单里的字段名（和 copy.field 不重复的部分）
  label: {
    orderDate: '下单日期',
    customerStore: '客户门店',
    customer: '客户',
    store: '门店',
    orderAmount: '订单金额',
    shipAmount: '发货金额',
    shipNote: '发货备注',
    origin: '来源',
    shippedBy: '发货人',
    shippedAt: '发货时间',
    cancelReason: '取消原因',
    cancelledAt: '取消时间',
    closeReason: '关闭原因',
    voidReason: '作废原因',
    voidedAt: '作废时间',
    sourceOrder: '原订单',
    afterAmount: '售后金额',
    processNote: '处理说明',
    afterReason: '问题原因',
    afterDescription: '问题说明',
    afterImages: '图片',
    afterDate: '提交日期',
    editReason: '修改原因',
    reason: '原因',
    name: '名称',
    enabled: '启用',
    loginPhone: '门店账号登录手机号',
    productImage: '产品图',
    material: '花材',
    bomQty: '用量',
    price: '单价',
    orderQty: '订单数量',
    shippedQty: '实发',
    after: '售后',
    receivable: '应收',
    received: '已收',
    unpaid: '未收',
    paid: '已付',
    due: '待付',
    prepaidBalance: '预收（未核销）',
    allocations: '核销记录',
    allocDetail: '核销明细',
    allocThis: '本次核销',
    receiptAmount: '收款金额',
    amount: '金额',
    methodShort: '方式',
    date: '日期',
    status: '状态',
    payStatus: '收款状态',
    newMethod: '新增',
    offsetByAfter: '（售后抵扣）',
    search: '搜索产品',
    searchOrders: '搜索单号、客户、门店',
    searchShipments: '搜索客户、门店',
  },
  tag: {
    changed: '改单',
    repriced: '改价',
    short: '少发',
    discontinued: '已停订',
    offset: '售后抵扣',
  },
  // 空状态「暂无 + 对象」
  empty: {
    shop: '可订产品',
    shopSearch: '相关产品',
    cart: '已选产品',
    orders: '订单',
    afters: '售后',
    afterable: '可申请售后的订单',
    statement: '发货单',
    todos: '待办',
    shipTodos: '待发货订单',
    shipments: '发货单',
    customers: '客户',
    products: '产品',
    directory: '目录产品',
    addableProducts: '可添加产品',
    addableMaterials: '可添加花材',
    arOrders: '已发货订单',
    records: '收付款记录',
  },
  confirm: {
    cancelOrder: '确认取消这张订单吗？',
    deleteCategory: '确认删除这个分类吗？',
    unbindStore: '门店下次打开要重新用手机号验证',
  },
  realtime: {
    refreshed: '这张单刚被修改，已刷新成最新内容',
    editing: '这张单刚被修改，点此查看最新内容',
  },
  // 列表卡片没有金额时（已关闭、已作废的售后）
  noAmount: '—',
  cartCount: (count: number) => `共 ${count} 件`,
  maxQty: (count: number) => `最多 ${count}`,
  bomCount: (count: number) => `配方 ${count} 种花材`,
  prepaid: (amount: string) => `预收 ${amount}`,
  storeUnpaid: (amount: string) => `未付 ${amount}`,
  arUnpaid: (amount: string) => `未收 ${amount}`,
  shippedSum: (amount: string) => `发货 ${amount}`,
  receivedSum: (amount: string) => `已收 ${amount}`,
  allocSummary: (allocated: string, prepaid: string) =>
    `本次核销 ${allocated} / 转为预收 ${prepaid}`,
  availablePrepaid: (amount: string) => `可用预收 ${amount}`,
  inviteExpires: (time: string) => `有效期至 ${time}`,
} as const
