import { formatMoney } from './format.ts'

export const reworkCopy = {
  afterImageRequired: '花材损坏、品质问题请至少上传 1 张图片',
  reasonRequired: '请填写原因',
  materialDuplicate: '同一花材只能出现一次',
  voidReasonRequired: '请填写作废原因',
  refundDateRequired: '请选择退款日期',
  revokeReasonRequired: '请填写撤回原因',
  requestCancel: '申请取消',
  withdrawCancel: '撤回取消申请',
  approveCancel: '同意取消',
  rejectCancel: '拒绝取消',
  cancelRequest: '取消申请',
  cancelRequests: '取消申请记录',
  cancelReason: '取消原因',
  rejectReason: '拒绝原因',
  rejectReasonRequired: '请填写拒绝原因',
  voidOrder: '作废订单',
  voidPurchaseOrder: '作废采购单',
  voidedBy: '作废人',
  apRepriceNotice: '这张单改过价，请核对应付金额',
  orderOperationLocked: '当前状态不能进行此操作',
  orderOperationStale: '订单状态或取消申请已变化，请刷新后重试',
  poVoidLocked: '当前状态不能作废采购单',
  poStale: '采购单已变化，请刷新后重试',
  cancelRequestReason: (reason: string) =>
    reason.trim() ? `门店申请取消：${reason.trim()}` : '门店申请取消',
  shipDifferenceNoteRequired: '实发和订单数量不一致，请写发货备注',
  overShipped: '多发',
  shipDifference: '发货差异',
  allocationHistory: '核销历史',
  refundHistory: '退款历史',
  revokeAllocation: '撤回核销',
  registerRefund: '登记退款',
  voidRefund: '作废退款',
  refundDate: '退款日期',
  refundAmount: '退款金额',
  refundMethod: '退款方式',
  refundNote: '退款备注',
  refundAmountRequired: '请填写大于 0 的退款金额',
  refundMethodRequired: '请选择退款方式',
  refundConfirm: '确认登记退款？退款后以全账重算结果为准。',
  revokeConfirm: '确认撤回核销？其他历史核销可能恢复生效，以重算后的余额为准。',
  receiptDetail: '收款详情',
  paymentDetail: '付款详情',
  availablePrepaid: '可用预付',
  availableReceiptPrepaid: '可用预收',
  allocatePaymentPrepaid: '核销预付',
  ledgerChanged: '账本已变化，请重新核对；当前填写内容已保留',
  ledgerStale: '账本已变化，请重新核对后再提交',
  recheck: '重新核对',
  keepDraft: '保留草稿',
  reviewBeforeSubmit: '提交前核对',
  continueSubmit: '继续提交',
  backToReview: '返回核对',
  allowOverGap: '允许超过当前缺口，请核对数量后继续',
  demandChanged: '需求已变化，请重新核对；当前填写内容已保留',
  noDemand: '当前没有采购需求',
  inTransitSources: '在途来源',
  copyCatalog: '复制目录',
  copySource: '复制来源',
  copyPreview: '复制预览',
  copyConfirm: '确认复制',
  noCopyableCatalog: '没有可复制的目录项',
  catalogChanged: '目录已变化，请重新预览',
  paymentAllocOver: '核销金额超过单据待付或本笔付款剩余金额',
  paymentPrepaidOver: '核销金额超过可用预付',
  refundOver: '退款金额超过本笔可用预收或预付',
  refundDateFuture: '退款日期不能晚于今天',
  allocationLocked: '核销已撤回或所属收付款已作废',
  paymentVoidLocked: '有有效退款，请先作废退款再作废付款',
  receiptVoidLocked: '有有效退款，请先作废退款再作废收款',
  paymentStale: '付款已变化，请刷新后重试',
  refundVoidLocked: '退款已作废',
  refundStale: '退款已变化，请刷新后重试',
  catalogCopySame: '不能复制到同一客户',
  catalogCopyNotEmpty: '目标客户目录不是空的，不能复制',
  catalogCopyStale: '来源或目标目录已变化，请重新预览',
  catalogCopyEmpty: '来源没有可复制的目录项',
  reviewStale: '供应商、花材或需求已变化，请重新核对',
  pendingInviteWarning: '已有待填报邀请，请核对后继续',
  gapChangedWarning: '缺口已变化，请复核；仍可按所填数量提交',
  inTransitNote: '在途不代表已到库',
  noShortage: '当前区间没有缺货花材',
  showAllMaterials: '显示全部花材',
  shortageOnly: '只看缺货',
  ledgerReviewed:
    '已刷新应收应付与凭据，金额、日期、方式及备注已保留；请重新填写核销金额并核对后提交',
  ledgerChanges: '本次重核变化',
  viewDocumentHistory: '查看单据及变更记录',
  copyReuseNote: '目标空分类按名称复用，不覆盖现有目录项',
  cancelPending: '取消申请中',
  submitCancelRequest: '提交申请',
  confirmWithdrawCancel: '确认撤回',
  cancelRequestReasonLabel: '申请原因',
  cancelRequestedAt: '申请时间',
  cancelHandledAt: '处理时间',
  paymentInfo: '付款信息',
  paymentAmount: '付款金额',
  confirmAllocatePaymentPrepaid: '确认核销预付',
  noUnpaidDocuments: '暂无待付款单据',
  copySkipped: (count: number) => `跳过 ${count} 个目录项`,
  paymentAllocSummary: (allocated: string, prepaid: string) =>
    `本次核销 ${allocated} / 转为预付 ${prepaid}`,
  paymentAvailablePrepaid: (amount: string) => `可用预付 ${amount}`,
  allocationAmounts: (registeredCents: number, effectiveCents: number) =>
    `登记 ${formatMoney(registeredCents)} · 生效 ${formatMoney(effectiveCents)}`,
  ledgerDifference: (beforeCents: number, afterCents: number) =>
    `待收或待付由 ${formatMoney(beforeCents)} 变为 ${formatMoney(afterCents)}，请重新核对`,
  noLongerUnpaid: (no: string) => `${no} 已不在当前待收或待付清单，请重新核对`,
  copySummary: (count: number) => `将复制 ${count} 个目录项`,
  overdueSummary: (count: number) => `${count} 张订单出货日期已过期，请先处理`,
} as const
export const recordsCopy = {
  orderChange: '变更记录',
  poChange: '改单记录',
  priceChange: '改价记录',
  returns: '退货记录',
  reason: (text: string) => `原因：${text}`,
} as const
