export const purchaseScreen = {
  repriceFrom: (from: string, to: string) => `改价 ${from} → ${to}`,
  receiveQty: (qty: number, received: number, returned: number, unit: string) =>
    `采购 ${qty} ${unit}\u3000\u3000实收 ${received} ${unit}\u3000\u3000退货 ${returned} ${unit}`,
  invitedPending: '已邀请（未提交，不算在途）',
  invitedLinePending: (suppliers: string[]) => `已邀请 ${suppliers.join('、')} 填报，还没提交`,
  supplierPlaceholder: '请选择供应商',
  notSupplied: '未供',
  extraSupply: '另报',
  supplyQty: (qty: number, unit: string) => `供 ${qty} ${unit}`,
  returnableQty: (qty: number, unit: string) => `可退 ${qty} ${unit}`,
  totalAmount: (amount: string, units: string) => `${amount}\u3000\u3000共 ${units}`,
  sourceShipDate: (date: string) => `出货日期 ${date}`,
  confirmReturn: '确认退货',
  confirmReprice: '确认改价',
  demandSearch: '搜索花材、供应商',
  shortageKinds: (count: number) => `${count} 种缺货`,
  overdueBar: (count: number) => `有 ${count} 张已过出货日期仍未发货的订单`,
  inviteNo: '邀请单号',
  gap: '缺口',
  inTransitPos: '在途采购单',
  productName: '产品',
  bomUsage: '用量',
  usageOf: (qty: number, unit: string, productUnit: string) => `${qty} ${unit}/${productUnit}`,
  myInvite: (no: string) => `填报 ${no}`,
  supplyOriginLine: (no: string) => `填报邀请 ${no}`,
  receiveRemark: '收货备注',
  returnedQty: (qty: number, unit: string) => `退货数量 ${qty} ${unit}`,
  materialSearch: '搜索花材名称、编码',
  kinds: (count: number) => `${count} 种`,
  timeLabel: '出入库时间',
  handler: '经办人',
  recentMoves: '最近出入库',
  allOfThisFlower: '这种花全部 ›',
  fifo: '先进先出',
  remaining: '剩余',
  inDate: '入库日期',
  pendingPos: (count: number) => `待收货 ${count} 单`,
  gapOf: (gap: number, unit: string) => `缺 ${gap} ${unit}`,
  gapChanged: (before: number, after: number, unit: string) => `缺 ${before} → ${after} ${unit}`,
  reviewTitle: '核对采购情况',
  materialLabel: '花材',
  currentGap: '当前缺口',
  backEdit: '返回修改',
  continueReview: '核对后继续',
  withCount: (text: string, count: number) => `${text}（${count}）`,
  poSearch: '搜索单号、供应商',
  supplierPoSearch: '搜索单号、花材',
  supplyAmount: '供货金额',
  supplyLabel: '供货',
  receivedDate: '收货日期',
  noShortageHere: '当前区间没有缺货花材',
} as const
