export const redesignCopy = {
  pendingOrderTodo: '待确认订单',
  pendingAfterTodo: '待处理售后',
  dueShipmentTodo: '今日应发',
  pendingInviteTodo: '待填报邀请',
  pendingPoTodo: '待收货采购单',
  afterImageRequired: '请至少上传 1 张图片',
  // 原因是「数量不符」（少发、漏发）时图片选填
  afterImagesOptional: '图片（选填）',
  duplicateOrder: '同一张订单不能重复选择',
  storeActor: (name: string) => `门店 ${name}`,
  supplierActor: (name: string) => `供应商 ${name}`,
  loginPhone: '登录手机号',
  staffSearch: '搜索姓名、手机号',
  contactHuazhong: '联系花众',
  contactMissing: '联系方式未设置',
  editMaterial: '修改花材',
  inviteDate: '邀请日期',
  need: '需求',
  inTransit: '在途',
  inStock: '库存',
  loss: '报损',
  stocktake: '盘点',
  productLines: '产品明细',
  materialLines: '花材明细',
  qty: '数量',
  actual: '实发',
  unit: '单位',
  price: '单价',
  subtotal: '小计',
  customerCode: '客户产品编码',
  materialCode: '花材编码',
  totalQty: '合计数量',
  totalAmount: '合计金额',
  confirm: '确定',
  common: '常用',
  masters: '资料',
  filter: '筛选',
  allSelected: '全选',
  picking: '配货',
  packed: (n: number, total: number) => `已配 ${n}/${total} 种`,
  waiting: '待定',
  notFilled: '未填',
  noChange: '没有修改',
  contact: '联系人',
  shipPrice: '发货单价',
  orderNote: (note: string) => `订单备注：${note}`,
  contactPhone: '联系电话',
  address: '地址',
  no: '单号',
  orderDate: '下单日期',
  shipDate: '出货日期',
  submittedAt: '提交时间',
  orderAmount: '订单金额',
  shippedAmount: '发货金额',
  purchaseAmount: '采购金额',
  opening: '已下单',
  confirmed: '已确认',
  shipped: '已发货',
  pendingConfirm: '待确认',
  toShip: '待发货',
  cancelled: '已取消',
  voided: '已作废',
  submitted: '已提交',
  processed: '已处理',
  pending: '待处理',
  closed: '已关闭',
  received: '已收货',
  receivedQty: '实收',
  receivedQtyFull: '实收',
  purchaseQty: '采购数量',
  toReceive: '待收货',
  rejected: '已拒收',
  invited: '已邀请',
  toSupply: '待填报',
  supply: '填报',
  orders: '订单',
  purchaseOrders: '采购单',
  statement: '对账单',
  unstatemented: '未对账',
  submitPo: '提交采购单',
  overdue: '有逾期未结清',
  overdueNotice: (name: string, amount: string, days: number) =>
    `${name}有逾期未结清 ${amount}，最早逾期 ${days} 天`,
  confirmMany: (n: number) => `确认订单（${n}）`,
  shipMany: (n: number) => `确认发货（${n}）`,
  confirmOrders: '确认订单',
  confirmWithEdit: '修改后确认',
  // 多选添加弹层的确认按钮
  addPicked: (n: number) => `添加（${n}）`,
  shipOrders: '确认发货',
  shipmentResult: (n: number, reason: string) => `${n} 单没发出：${reason}`,
  confirmationResult: (n: number, reason: string) => `${n} 单没确认：${reason}`,
  moreOrders: (n: number) => `等 ${n} 单`,
  shipConfirmation: '实发按订单数量确认',
  delivery: '送货单',
  rejectPurchaseTitle: '拒收采购单？',
  rejectPurchaseBody: '全部实收记为 0，不计入库存和对账。',
  rejectPurchaseConfirm: '拒收',
  rejectLine: '拒收此行',
  lineRejected: '已拒收',
  pickedCount: (n: number, qty: string) => `已选 ${n} 款\u3000\u3000${qty}`,
  saveImage: '保存图片',
  shareImage: '发给微信好友',
  savedImage: '图片已保存',
  albumDeniedTitle: '需要相册权限',
  albumDeniedBody: '保存图片要用到相册，请在设置里打开「保存到相册」后再试。',
  albumDeniedConfirm: '去设置',
  signature: '收货人签字',
  signedDate: '签收日期',
  shipper: '发货人',
  shippedAt: '发货时间',
  stockAge: '库龄',
  cancelPendingNotice: (actor: string, at: string, reason: string) =>
    `取消申请待处理\u3000\u3000申请人 ${actor}\u3000\u3000提交时间 ${at}\u3000\u3000原因 ${reason || '未填'}`,
  cancelRejectedNotice: (reason: string) =>
    reason.trim() ? `取消申请被拒绝：${reason.trim()}` : '取消申请被拒绝',
  cancelUnhandledNotice: '已发货，取消申请未处理',
  imageActionFailed: '图片操作失败，请重试',
  stores: '门店',
  oldStock: '放久了 · 先用',
  otherStock: '其他',
  age: (n: number) => `已放 ${n} 天`,
  agedCount: '放久了',
  receiving: '收货',
  stock: '库存',
  stocktakeRecords: '盘点记录',
  returns: '退货',
  repricing: '改价',
  cancelApplication: '取消申请',
  source: '来源',
  submittedDate: '提交日期',
  afterAmount: '售后金额',
  originalOrder: '原订单',
  imageCountText: (n: number) => `图片 ${n} 张`,
  appliedQty: '申请数量',
  handledQty: '处理数量',
  tomorrow: '明天',
  next7Days: '未来 7 天',
  all: '全部',
  shortage: '缺货',
  notShippedYet: '这张订单还没发货，没有送货单',
  orderAction: {
    cancel: { body: '取消后这张订单不能恢复', done: '订单已取消' },
    approveCancel: {
      body: '同意后订单变为已取消，取消原因记为「门店申请取消」',
      done: '已同意取消，订单已取消',
    },
    rejectCancel: {
      body: '拒绝后门店能看到原因，这张单不能再申请取消',
      done: '已拒绝取消申请',
    },
    voidOrder: { body: '作废后这张订单变为已作废，作废原因会记下来', done: '订单已作废' },
  },
  confirmedMany: (n: number) => `已确认 ${n} 单`,
  shippedMany: (n: number) => `已发货 ${n} 单`,
  confirmSheetTitle: (n: number) => `确认订单 · ${n} 单`,
  confirmSheetNote: '产品、数量、单价都不改；要改的请点进单子单独确认',
  shipSummary: (n: number) => `共 ${n} 单，实发都按订单数量`,
  shipDifferenceHint: '有少发、多发的请点进单子单独改',
  product: '产品',
  packedState: (n: number, total: number) =>
    n >= total ? `已配好 ${n}/${total} 种` : `未配 ${n}/${total} 种`,
  inviteSheetTitle: '邀请订货',
  inviteStorePick: '门店',
  inviteNoStore: '没有可邀请的门店：需要启用、已填登录手机号、还没绑定微信',
  inviteNoStoreAll: '没有可邀请的门店：需要启用的客户和门店',
  inviteSearch: '搜索客户、门店',
  inviteNoRight: '你没有修改门店资料的权限，请联系有权限的同事填写登录手机号',
  inviteLoginPhoneHint: '填好 11 位登录手机号后点「保存并邀请」',
  inviteSaveAndInvite: '保存并邀请',
  inviteContactHint: '开通门店账号需要先填写联系人',
  inviteRepick: '换一家门店',
  inviteNoPhone: '未填登录手机号',
  inviteNoMatch: '没有匹配的门店',
  inviteReady: '邀请已生成，点「发给门店」转发给对方',
  inviteSavingPhone: '正在保存登录手机号并生成邀请',
  due: '今天及以前出货',
  dueFilter: '出货',
} as const
