// 界面文案：每句只在这里定义一次，前后端引用同一个键（00 章第 10 节）。
// 出处：02 章第 5 节（通用状态）、05 章（接口返回的句子）、06 章（各页文案）。

import { screen } from './copy-screen.ts'

// 同一行里并列的几项之间（身份行、卡片第 3 行）
const SEPARATOR = ' · '

export const copy = {
  separator: SEPARATOR,
  error: {
    unauthenticated: '没有绑定账号',
    accountDisabled: '账号已停用，请联系花众',
    storeDisabled: '这家门店已停用，请联系花众',
    supplierDisabled: '这家供应商已停用，请联系花众',
    forbidden: '没有权限查看这个页面',
    notFound: '没有找到这张单据',
    internal: '系统出错了，请稍后再试',
    validationFallback: '格式不对，请检查后重试',
    dateRange: '结束日期不能早于开始日期',
    noChange: '没有修改内容',
  },
  // 登录绑定（05 章第 2 节）
  auth: {
    phoneNotRegistered: '这个手机号还没开通，请联系花众管理员',
    boundToOtherWechat: '这个账号已绑定其他微信，请联系管理员解绑',
    phoneCodeInvalid: '手机号验证失败，请重试',
    loginButton: '手机号快速验证登录',
    privacyPrefix: '我已阅读并同意',
    privacyContract: '《花众小程序隐私保护指引》',
    privacyRequired: '请先阅读并同意隐私保护指引',
  },
  // 员工与岗位（05 章第 3 节、06 章 M7）
  staff: {
    nameRequired: '请填写名字',
    phoneInvalid: '请填写 11 位登录手机号',
    phoneTaken: '这个手机号已经被其他账号使用',
    modulesRequired: '请至少选一个模块',
    lastAdmin: '至少要保留一个启用的管理员',
    stale: '这个员工刚被修改，已刷新成最新内容',
    notBound: '这个员工还没绑定微信',
    unbindTogether: '同时解绑微信',
    roleSeparator: '、',
  },
  // 账号类操作日志（05 章第 2 节）：module 为空 = 公共
  log: {
    kindAccount: '账号',
    bind: '绑定微信',
    unbind: '解绑微信',
    createStaff: '新增员工',
    updateStaff: '修改员工',
    publicModule: '公共',
    reason: '原因',
    before: '修改前',
    after: '修改后',
    changes: '改动',
    // 改动「旧 → 新」里旧值后面接的箭头
    arrow: ' → ',
    date: '操作日期',
    // 阶段 3 的对象类别和动作（04 章第 3.3 节 kind、action）
    kind: {
      order: '订单',
      after: '售后',
      customer: '客户',
      store: '门店',
      product: '产品',
      category: '分类',
      catalog: '订货目录',
      receipt: '收款',
      method: '收付款方式',
    },
    action: {
      createOrder: '新建订单',
      confirmOrder: '确认订单',
      editAndConfirm: '修改并确认订单',
      editOrder: '修改订单',
      cancelOrder: '取消订单',
      storeOrder: '门店下单',
      storeEdit: '门店改单',
      storeCancel: '门店取消订单',
      shipOrder: '确认发货',
      applyAfter: '申请售后',
      createAfter: '新建售后',
      processAfter: '处理售后',
      closeAfter: '关闭售后',
      voidAfter: '作废售后',
      createCustomer: '新增客户',
      updateCustomer: '修改客户',
      createStore: '新增门店',
      updateStore: '修改门店',
      inviteStore: '生成门店邀请',
      acceptInvite: '门店接受邀请',
      unbindStore: '解绑门店微信',
      createProduct: '新增产品',
      updateProduct: '修改产品',
      createCategory: '新增分类',
      updateCategory: '修改分类',
      orderCategories: '调整分类顺序',
      deleteCategory: '删除分类',
      updateCatalog: '修改订货目录',
      registerReceipt: '登记收款',
      allocatePrepaid: '核销预收',
      voidReceipt: '作废收款',
      createMethod: '新增收付款方式',
      enableMethod: '启用收付款方式',
      disableMethod: '停用收付款方式',
    },
  },
  // 账号字段名：员工弹层、个人资料、日志的修改前后共用
  field: {
    name: '名字',
    phone: '登录手机号',
    role: '岗位',
    status: '状态',
    admin: '管理员',
    modules: '模块',
    org: '所属',
    wechat: '微信',
    // 阶段 3：客户、门店、产品、订单、收款的修改前后
    contact: '联系人',
    storePhone: '电话',
    address: '地址',
    shipDate: '出货日期',
    note: '备注',
    category: '分类',
    unit: '单位',
    bom: '配方',
    listPrice: '订货价',
    catalogCategory: '订货分类',
    customerCode: '客户产品编码',
    amount: '金额',
    method: '收款方式',
    receiptDate: '收款日期',
    sort: '顺序',
  },
  statusValue: {
    enabled: '启用',
    disabled: '停用',
    bound: '已绑定',
    orderable: '可订',
    discontinued: '停用',
  },
  store: {
    customerDisabled: '这个客户已停用，不能再下新单，请联系花众',
    customerDisabledEdit: '这个客户已停用，不能再修改订单，请联系花众',
    removedFromCart: (names: string) => `${names}已停用，已从购物车移除`,
    orderableCount: (count: number) => `今日可订 ${count} 款`,
  },
  // 订单、发货（03 章第 5、8.1 节，05 章第 4–6 节）
  order: {
    shipDatePending: '待销售安排',
    shipDateRequired: '请选择出货日期',
    editReasonRequired: '请填写修改原因',
    linesRequired: '请添加产品并填写有效数量',
    storeLinesRequired: '请先选择产品',
    qtyInvalid: '数量须为大于 0 的整数',
    priceRequired: '请填写单价',
    duplicateProduct: '同一种产品只能添加一次',
    shipOverQty: '实发不能超过订单数量',
    // 几个产品名之间
    nameSeparator: '、',
    // 日志里一行明细：「20 束 × ¥68.00」
    lineView: (qtyText: string, priceText: string) => `${qtyText} × ${priceText}`,
    storeRequired: '请选择客户和门店',
    discontinuedSave: (names: string) => `${names}已停用，请先删掉再保存`,
    discontinuedSubmit: (names: string) => `${names}已停用，请先删掉再提交`,
    discontinuedConfirm: (names: string) => `${names}已停用，请修改并确认或取消订单`,
    productUnavailable: (name: string) => `${name}不在这个客户的可订产品里`,
    storeDisabledConfirm: '门店已停用，启用后才能确认',
    customerDisabledConfirm: '客户已停用，启用后才能确认',
    customerDisabledNew: '这个客户已停用，不能再下新单',
    storeDisabledNew: '门店已停用，不能下单',
    cancelledStale: '订单已被取消，不能再修改',
    confirmedStoreStale: '销售已确认，门店不能再修改，请联系销售',
    confirmedStoreCancel: '销售已确认，请联系销售取消',
    confirmedLocked: '销售已确认，如需修改请联系花众销售',
    confirmedStale: '订单已被确认，已刷新成最新内容',
    shippedLocked: '订单已发货，不能再修改',
    shippedAlready: '这张订单已经发货',
    cancelledAlready: '订单已被取消',
    stale: '订单刚被修改过，已刷新成最新内容，请核对后再保存',
    shipCancelled: '销售已取消这张订单，不能发货',
    shipChanged: '销售修改了这张订单，已刷新成最新内容，请核对后再确认发货',
    shipNotDue: '出货日期还没到，不能发货',
    shipNoteRequired: '少发时请填写发货备注',
    shipNothing: '至少发出一项产品；整单不发请联系销售取消订单',
    allAftered: '这张订单的产品都已申请过售后',
    afterExpired: '已超过售后申请时间，请联系花众销售',
    reasonRequired: '请填写原因',
    moreItems: (name: string, count: number) => `${name} 等 ${count} 项`,
    change: {
      qty: (name: string, from: number, to: number) => `${name} 数量 ${from} → ${to}`,
      price: (name: string, from: string, to: string) => `${name} 单价 ${from} → ${to}`,
      shipDate: (from: string, to: string) => `出货日期 ${from} → ${to}`,
      added: (name: string, qty: number, unit: string) => `添加 ${name} ${qty} ${unit}`,
      removed: (name: string) => `删除 ${name}`,
      note: '修改备注',
    },
    syncedByCatalog: (nos: string) => `同步待确认订单 ${nos}`,
    confirmed: '订单已确认',
    cancelled: '订单已取消',
    shipped: '已发货',
  },
  // 售后（03 章第 4、5、8.1 节，05 章第 4、5 节）
  after: {
    linesRequired: '请添加售后产品',
    salesLinesRequired: '请添加售后产品并填写有效数量',
    reasonRequired: '请选择售后原因',
    descriptionRequired: '请填写每项产品的问题说明',
    storeQtyInvalid: '售后数量须大于 0，且不超过实发数量减去已申请的售后',
    qtyOverMax: '售后数量不能超过实发数量减去已申请的售后',
    processQtyInvalid: '售后数量须为 0 或正整数，不给的填 0',
    allZero: '数量都是 0，整张不处理请关闭售后并写原因',
    priceOverShip: (name: string, price: string) => `${name}的售后单价不能高于发货单价 ${price}`,
    linesLocked: '门店提交的售后只能改数量和单价',
    orderNotShipped: '订单还没发货，不能申请售后',
    processedNotice: '发货单应收已减去售后金额',
    pendingAmount: '待确认',
    closeReasonRequired: '请填写关闭原因',
    voidReasonRequired: '请填写作废原因',
    stale: '售后刚被处理过，已刷新成最新内容',
    imagesTooMany: (max: number) => `每项产品最多 ${max} 张图片`,
    imageInvalid: '图片没有上传成功，请重试',
    processed: '售后已处理',
    closed: '售后已关闭',
    voided: '售后已作废',
  },
  // 客户、门店、产品、分类、订货目录（03 章第 8.1 节，05 章第 4 节）
  catalog: {
    customerRequired: '请选择客户',
    bomQtyInvalid: '用量须为大于 0 的整数',
    listPriceRequired: '请填写订货价',
    customerNameRequired: '请填写客户名称',
    customerNameTaken: '已有同名客户',
    storeNameRequired: '请填写门店名称',
    storeNameTaken: '这个客户下已有同名门店',
    contactRequired: '开通门店账号请填写联系人',
    loginPhoneInvalid: '请填写 11 位登录手机号',
    loginPhoneTaken: '这个手机号已经被其他账号使用',
    storeNotBound: '这家门店账号还没绑定微信',
    storeBound: '这家门店账号已绑定微信，请联系销售解绑',
    loginPhoneMissing: '请先在门店资料里填写登录手机号',
    storeDisabledInvite: '门店已停用，启用后才能邀请下单',
    customerStale: '客户刚被修改，已刷新成最新内容',
    storeStale: '门店刚被修改，已刷新成最新内容',
    productNameRequired: '请填写产品名称',
    productNameTaken: '已有同名产品',
    categoryRequired: '请选择分类',
    unitRequired: '请填写单位',
    bomRequired: '请至少添加一种花材',
    bomDuplicate: '同一种花材只能添加一次',
    bomMaterialUnavailable: '配方里的花材不存在或已停用',
    productStale: '产品刚被修改，已刷新成最新内容',
    categoryNameRequired: '请填写分类名称',
    categoryNameTaken: '已有同名分类',
    categoryNotEmpty: '分类中仍有产品，请先移动产品',
    categoryStale: '分类刚被修改，已刷新',
    productDisabledForCatalog: (name: string) => `${name}已停用，不能加进订货目录`,
    catalogStale: '订货目录刚被修改，已刷新成最新内容',
    catalogCategoryRequired: '请选择订货分类',
    customerCodeTaken: '这个客户下已有相同的产品编码',
    catalogCategoryNotEmpty: '分类中仍有目录产品，请先换分类',
    // 目录弹层里改了配方，保存前确认（配方是产品本身的，所有客户共用）
    sharedBomTitle: '配方所有客户共用',
    sharedBomBody: '改后所有客户的这个产品都会变。',
  },
  // 财务收款部分（03 章第 4、8.4 节，05 章第 10 节）
  finance: {
    amountRequired: '请填写收款金额',
    methodRequired: '请选择收款方式',
    receiptDateRequired: '请选择收款日期',
    duplicateOrder: '同一张发货单只能填一行',
    methodDisabled: '这种收款方式已停用，请换一种',
    receiptDateFuture: '收款日期不能晚于今天',
    payDateFuture: '付款日期不能晚于今天',
    allocOver: (no: string, max: string) => `${no} 最多核销 ${max}`,
    allocTotalOver: '核销合计不能超过收款金额',
    prepaidOver: (max: string) => `可用预收只有 ${max}`,
    allocRequired: '请填写核销金额',
    voidReasonRequired: '请填写作废原因',
    receiptVoidedNotice: '已作废，核销已撤回。',
    receiptStale: '这笔收款刚被作废，已刷新',
    methodNameRequired: '请填写名称',
    methodNameTaken: '已有同名方式',
    lastMethod: '至少要保留一种启用的方式',
    received: '已收款',
    allocated: '已核销',
    receiptVoided: '收款已作废',
  },
  // 门店邀请下单（03 章第 8.1 节，05 章第 2、4 节）
  invite: {
    storeTitle: '花众邀请你在线订货',
    invalid: '邀请已失效，请联系花众销售重新发送',
    phoneMismatch: '手机号和门店登记的不一致，请用登记的手机号验证',
    otherAccount: (name: string) => `这台微信已登录${name}，请先在「我的」退出登录再接受邀请`,
    goMy: '去我的',
  },
  // 图片上传（05 章第 11 节）
  file: {
    missing: '图片没有上传成功，请重试',
    rejected: '图片未通过审核，请换一张',
    tooLarge: '图片太大了，请换一张',
    badType: '只能上传 jpg、png、webp 图片',
  },
  // 底栏（02 章第 4 节 hz-tabbar）
  tab: {
    home: '首页',
    my: '我的',
  },
  // 门店首页、供应商首页的主卡和小卡（03 章第 8.5 节）
  hub: {
    order: '订货',
    orders: '订单',
    afters: '售后',
    statement: '对账',
    supply: '填报',
    purchaseOrders: '采购单',
  },
  // 列表的对象名：空状态「暂无 + 对象」、搜索框、筛选项
  object: {
    inventory: '库存',
    logs: '操作日志',
    staff: '员工',
    material: '花材',
    category: '分类',
    module: '模块',
  },
  tag: {
    disabled: '已停用',
  },
  network: {
    loadFailed: '网络不太好，没有加载出来',
    refreshFailed: '刷新失败，请重试',
    submitFailed: '网络不太好，没有提交成功，请重试',
  },
  // 操作日志、变更记录里的操作人快照（04 章第 3.3 节）
  actor: {
    system: '系统',
    external: (name: string, org: string) => `${name}（${org}）`,
  },
  org: {
    store: (customerName: string, storeName: string) => `${customerName}${SEPARATOR}${storeName}`,
  },
  // 页面标题：思源宋体子集从这里抽字（scripts/gen-font）
  title: {
    devGallery: '组件总览',
    filter: '筛选',
    my: '我的',
    inventory: '库存查询',
    logs: '操作日志',
    logDetail: '日志详情',
    staff: '员工与岗位',
    staffCreate: '新增员工',
    staffEdit: '编辑员工',
    profile: '个人资料',
  },
  // 统一状态（02 章第 5 节）；state、confirm 里的句子用衬线字，也进字体子集
  state: {
    loading: '加载中',
    empty: (object: string) => `暂无${object}`,
    offline: '网络已断开，恢复后自动刷新',
    linkInvalid: '邀请已失效',
    allLoaded: '已显示全部',
  },
  confirm: {
    discardTitle: '放弃修改吗？',
    discardBody: '刚填的内容不会保存',
    keepEditing: '继续填写',
    discard: '放弃修改',
    logoutTitle: '退出登录吗？',
    logoutBody: '下次进入要重新用手机号验证',
    unbindTitle: '解绑微信吗？',
    unbindBody: '对方下次打开要重新用手机号验证',
    cancel: '取消',
  },
  action: {
    retry: '重试',
    back: '返回',
    logout: '退出登录',
    submitting: '提交中',
    clear: '清除',
    // 按钮写动作 + 对象（02 章第 8 节，2026-10-05 确认）
    saveCategory: '保存分类',
    saveMethod: '保存方式',
    saveCustomer: '保存客户',
    saveStore: '保存门店',
    saveProduct: '保存产品',
    saveCatalogItem: '保存目录项',
    saveStaff: '保存员工',
    saveAfter: '保存售后',
    confirmSave: '确认保存',
    saved: '已保存',
    unbound: '已解绑',
  },
  requestId: (id: string) => `请求编号 ${id}`,
  unit: { yuan: '元' },
  // 筛选栏（02 章第 4 节 hz-filter-bar）
  filter: {
    all: '全部',
    today: '今天',
    last7Days: '近 7 天',
    thisMonth: '本月',
    custom: '自定义',
    dateFrom: '开始日期',
    dateTo: '结束日期',
    range: (from: string, to: string) => `${from} 至 ${to}`,
    allOf: (object: string) => `全部${object}`,
    choose: (object: string) => `选择${object}`,
    search: (object: string) => `搜索${object}`,
  },
  // 记录列表标题（hz-records）
  records: {
    orderChange: '变更记录',
    poChange: '改单记录',
    priceChange: '改价记录',
    returns: '退货记录',
    reason: (text: string) => `原因：${text}`,
  },
  placeholder: {
    choose: '请选择',
    optional: '选填',
  },
  // 阶段 3 页面（06 章 S1–S9、X1–X11、H1–H3、F1–F9、M2）
  screen,
} as const
