import { purchaseScreen } from './copy-purchase.ts'
// 阶段 3 页面的文案（06 章 S1–S9、X1–X11、H1–H3、F1–F9、M2）：copy.screen，和 copy.ts 同一个出处规则
export const screen = {
  // 页面、弹层标题和模块首页入口名：思源宋体子集从这里抽字（scripts/gen-font）
  title: {
    shop: '订货',
    cart: '购物车',
    storeOrders: '订单',
    checkout: '结算',
    orderDetail: '订单详情',
    storeAfters: '售后',
    applyAfter: '申请售后',
    statement: '对账',
    salesOrders: '销售订单',
    createOrder: '新建订单',
    editOrder: '修改订单',
    editAndConfirm: '修改并确认',
    confirmOrder: '确认订单',
    salesAfters: '客户售后',
    afterDetail: '售后详情',
    createAfter: '新建售后',
    processAfter: '处理售后',
    customers: '客户门店',
    createCustomer: '新建客户',
    editCustomer: '编辑客户',
    createStore: '新建门店',
    editStore: '编辑门店',
    inviteStore: '邀请下单',
    products: '产品管理',
    createProduct: '新建产品',
    editProduct: '编辑产品',
    categories: '管理分类',
    addCategory: '新增分类',
    renameCategory: '修改分类',
    catalogItem: '目录产品',
    directory: '订货目录',
    shipList: '发货单',
    ship: '发货',
    arCustomers: '客户对账',
    arCustomer: '客户对账详情',
    registerReceipt: '登记收款',
    allocate: '核销预收',
    receipt: '收款详情',
    records: '收付款记录',
    methods: '收付款方式',
    addReceiveMethod: '新增收款方式',
    addPayMethod: '新增付款方式',
    pickOrder: '选择订单',
    pickProduct: '选择产品',
    pickMaterial: '选择花材',
    picked: '已选产品',
    todos: '待办',
    demand: '采购需求',
    purchaseOrders: '采购单',
    purchaseOrder: '采购单详情',
    createPo: '新建采购单',
    editPo: '修改采购单',
    invites: '供应商填报',
    supply: '填报',
    createInvite: '发出邀请',
    editInvite: '修改邀请',
    invite: '填报详情',
    suppliers: '供应商',
    createSupplier: '新建供应商',
    editSupplier: '修改供应商',
    receive: '收货',
    pendingReceive: '待收',
    stock: '库存',
    materials: '花材',
    material: '花材详情',
    apSuppliers: '供应商对账',
    apSupplier: '供应商对账详情',
    payable: '单据付款',
    payment: '付款详情',
  },
  tab: { cart: '购物车', supply: '填报' },
  // 按钮：单据级操作码的按钮名（05 章第 1.5 节）和页面按钮
  action: {
    storeEdit: '修改订单',
    storeCancel: '取消订单',
    applyAfter: '申请售后',
    confirm: '确认订单',
    editAndConfirm: '修改并确认',
    edit: '修改订单',
    cancel: '取消订单',
    createAfter: '新建售后',
    ship: '确认发货',
    processAfter: '处理售后',
    closeAfter: '关闭售后',
    voidAfter: '作废售后',
    allocate: '核销预收',
    registerReceipt: '登记收款',
    voidReceipt: '作废收款',
    inviteStore: '邀请下单',
    unbindStoreWechat: '解绑微信',
    createOrder: '新建订单',
    createCustomer: '新建客户',
    createStore: '新建门店',
    editCustomer: '编辑客户',
    createProduct: '新建产品',
    manageCategories: '管理分类',
    addCategory: '新增分类',
    addProduct: '添加产品',
    addMaterial: '添加花材',
    toCheckout: '去结算',
    submitOrder: '提交订单',
    confirmEdit: '确认修改',
    saveEdit: '保存修改',
    submitAfter: '提交售后',
    confirmReceipt: '确认收款',
    confirmAllocate: '确认核销',
    fill: '填入',
    clear: '清空',
    viewAll: '查看全部',
    shipRecords: '发货记录',
    generateInvite: '生成邀请',
    shareInvite: '发送给门店',
    goMy: '去我的',
    confirmCancel: '确认取消',
    confirmClose: '确认关闭',
    confirmVoid: '确认作废',
    moveUp: '上移',
    delete: '删除',
    next: '下一步',
    viewSupply: '查看填报',
    createPo: '生成采购单',
    confirmPo: '确认下单',
    editPo: '修改采购单',
    cancelPo: '取消采购单',
    inviteSupplier: '邀请供应商',
    editInvite: '修改邀请',
    cancelInvite: '取消邀请',
    sendSupply: '发送填报邀请',
    supplyLink: '填报链接',
    copyLink: '复制链接',
    submitSupply: '提交填报',
    extraMaterial: '另报花材',
    receive: '确认收货',
    return: '退货',
    reprice: '改单价',
    pay: '登记付款',
    confirmPayment: '确认付款',
    voidPayment: '作废付款',
    viewPayment: '查看付款',
    createMaterial: '新建花材',
    saveSupplier: '保存供应商',
    saveMaterial: '保存花材',
  },
  // 详情、表单里的字段名（和 copy.field 不重复的部分）
  label: {
    orderDate: '下单日期',
    customerStore: '客户门店',
    customer: '客户',
    store: '门店',
    orderAmount: '订单金额',
    shipAmount: '发货金额',
    shipNote: '发货备注',
    origin: '来源',
    shippedBy: '发货人',
    shippedAt: '发货时间',
    cancelReason: '取消原因',
    cancelledAt: '取消时间',
    closeReason: '关闭原因',
    voidReason: '作废原因',
    voidedAt: '作废时间',
    sourceOrder: '原订单',
    afterAmount: '售后金额',
    processNote: '处理说明',
    afterReason: '问题原因',
    afterDescription: '问题说明',
    afterImages: '图片',
    afterDate: '提交日期',
    editReason: '修改原因',
    reason: '原因',
    name: '名称',
    enabled: '启用',
    loginPhone: '门店账号登录手机号',
    customerCode: '客户产品编码',
    catalogCategory: '订货分类',
    productImage: '产品图',
    material: '花材',
    bomQty: '用量',
    price: '单价',
    orderQty: '订单数量',
    after: '售后',
    receivable: '应收',
    received: '已收',
    unpaid: '未收',
    paid: '已付',
    due: '待付',
    prepaidBalance: '预收（未核销）',
    allocations: '核销记录',
    allocDetail: '核销明细',
    allocThis: '本次核销',
    receiptAmount: '收款金额',
    amount: '金额',
    total: '合计',
    methodShort: '方式',
    date: '日期',
    offsetByAfter: '（售后抵扣）',
    search: '搜索产品',
    searchOrders: '搜索单号、客户、门店',
    searchShipments: '搜索客户、门店',
    supplier: '供应商',
    buyer: '采购员',
    supplierAccount: '开通供应商端账号',
    supplierLoginPhone: '供应商账号登录手机号',
    recordType: '类型',
    purchaseAmount: '采购金额',
    payable: '应付',
    receivedQty: '实收',
    returnedQty: '退货',
    receiveNote: '收货备注',
    repriceReason: '改价原因',
    from: '出货日期起',
    to: '出货日期止',
    paymentDate: '付款日期',
    paymentMethod: '付款方式',
  },
  // 详情、表单里分组的小标题（第一张信息卡不写）
  section: {
    customerItem: '订货信息',
    sharedBom: '配方明细',
    lines: '产品明细',
    afterLines: '售后明细',
    bom: '配方明细',
    ship: '发货信息',
    cancel: '取消信息',
    close: '关闭信息',
    void: '作废信息',
    allocs: '核销明细',
    // 整页表单的组标题（2026-10-05 确认：组标题 + 卡片）
    basic: '基本信息',
    display: '展示',
    orderInfo: '订单信息',
    receipt: '收款信息',
    materials: '花材明细',
    supply: '我的填报',
    batches: '库存批次',
  },
  tag: {
    changed: '改单',
    repriced: '改价',
    short: '少发',
    discontinued: '已停用',
    offset: '售后抵扣',
  },
  // 空状态「暂无 + 对象」
  empty: {
    shop: '可订产品',
    shopSearch: '相关产品',
    cart: '已选产品',
    orders: '订单',
    afters: '售后',
    afterable: '可申请售后的订单',
    statement: '发货单',
    todos: '待办',
    shipTodos: '待发货订单',
    shipments: '发货单',
    customers: '客户',
    products: '产品',
    directory: '目录产品',
    categories: '分类',
    addableProducts: '可添加产品',
    addableMaterials: '可添加花材',
    arOrders: '已发货订单',
    records: '收付款记录',
    purchaseOrders: '采购单',
    invites: '邀请',
    suppliers: '供应商',
    materials: '花材',
    payables: '应付单据',
    demand: '待发货订单',
  },
  confirm: {
    cancelOrder: '确认取消这张订单吗？',
    deleteCategory: '确认删除这个分类吗？',
    unbindStore: '门店下次打开要重新用手机号验证',
  },
  realtime: {
    refreshed: '这张单刚被修改，已刷新成最新内容',
    editing: '这张单刚被修改，点此查看最新内容',
  },
  // 列表卡片没有金额时（已关闭、已作废的售后）
  noAmount: '—',
  cartCount: (count: number) => `共 ${count} 件`,
  maxQty: (count: number) => `最多 ${count}`,
  bomCount: (count: number) => `配方 ${count} 种花材`,
  needCategory: '请先新增订货分类',
  sharedBomNote: '配方所有客户共用，改了所有客户都会变',
  // 目录行的订货价「¥68.00/束」、弹层里订货价的标签「订货价（元/束）」
  pricePer: (price: string, unit: string) => `${price}/${unit}`,
  priceLabel: (unit: string) => `订货价（元/${unit}）`,
  prepaid: (amount: string) => `预收 ${amount}`,
  storeUnpaid: (amount: string) => `未付 ${amount}`,
  arUnpaid: (amount: string) => `未收 ${amount}`,
  shippedSum: (amount: string) => `发货 ${amount}`,
  receivedSum: (amount: string) => `已收 ${amount}`,
  allocSummary: (allocated: string, prepaid: string) =>
    `本次核销 ${allocated} / 转为预收 ${prepaid}`,
  availablePrepaid: (amount: string) => `可用预收 ${amount}`,
  inviteExpires: (time: string) => `有效期至 ${time}`,
  orderCount: (count: number) => `${count} 张订单`,
  demandNumbers: (need: number, stock: number, transit: number) =>
    `需求 ${need} · 库存 ${stock} · 在途 ${transit}`,
  leftQty: (qty: number) => (qty < 0 ? `缺 ${-qty}` : `余 ${qty}`),
  invited: '已邀请',
  ...purchaseScreen,
  pickSupplier: '请选择一家供应商',
  noPaymentNeeded: '这张单已不需要付款',
  needQty: (qty: number, unit: string) => `需求 ${qty} ${unit}`,
  purchaseQty: (qty: number, unit: string) => `采购 ${qty} ${unit}`,
  shortReceived: (qty: number) => `少收 ${qty}`,
  overReceived: (qty: number) => `多收 ${qty}`,
  stockQty: (qty: number, unit: string) => `库存 ${qty} ${unit}`,
  openPoCount: (count: number) => `待收货 ${count} 单`,
  supplyPending: (count: number) => `${count} 份邀请待填报`,
  inviteEdited: '邀请已修改，供应商看到的是最新内容',
  supplyEdited: '采购修改了这次邀请，点此查看最新内容',
  inviteSent: (name: string) => `已邀请${name}填报，可以发送填报链接提醒对方`,
  purchaseOrigin: '花众采购下单',
  supplyOrigin: (no: string) => `供应商填报 · ${no}`,
  noInviteSupplier: '暂无已开通供应商端账号的供应商',
  allReturned: '已全部退货',
} as const
// 收付款及采购链路的字段提示；通过 copy.finance 对前后端提供同一份文案。
export const financeCopy = {
  amountRequired: '请填写收款金额',
  methodRequired: '请选择收款方式',
  receiptDateRequired: '请选择收款日期',
  duplicateOrder: '同一张发货单只能填一行',
  methodDisabled: '这种收款方式已停用，请换一种',
  receiptDateFuture: '收款日期不能晚于今天',
  payDateFuture: '付款日期不能晚于今天',
  payDateRequired: '请选择付款日期',
  paymentMethodRequired: '请选择付款方式',
  allocOver: (no: string, max: string) => `${no} 最多核销 ${max}`,
  allocTotalOver: '核销合计不能超过收款金额',
  prepaidOver: (max: string) => `可用预收只有 ${max}`,
  allocRequired: '请填写核销金额',
  voidReasonRequired: '请填写作废原因',
  receiptVoidedNotice: '已作废，核销已撤回。',
  receiptStale: '这笔收款刚被作废，已刷新',
  methodNameRequired: '请填写名称',
  methodNameTaken: '已有同名方式',
  lastMethod: '至少要保留一种启用的方式',
  received: '已收款',
  allocated: '已核销',
  receiptVoided: '收款已作废',
  paymentVoided: '付款已作废',
  supplierNameRequired: '请填写供应商名称',
  supplierNameTaken: '已有同名供应商',
  supplierAccountRequired: '开通供应商端账号请填写 11 位登录手机号',
  poSupplierRequired: '请选择供应商',
  poLinesRequired: '请至少添加一种花材',
  poQtyInvalid: '采购数量须为大于 0 的整数',
  poPriceRequired: '请填写单价，赠送的花材填 0',
  poReasonRequired: '请填写修改原因',
  poCancelReasonRequired: '请填写取消原因',
  poCannotChangeSupplier: '填报生成的采购单不能换供应商，要换请取消后重下',
  poCancelled: '采购单已取消',
  inviteSupplierAccount: '这家供应商还没有开通供应商端账号',
  inviteMaterialDisabled: '花材已停用，请删掉这一行再提交',
  inviteAllZero: '请至少保留一种花材；全部不供请联系采购取消邀请',
  inviteStale: '采购修改了邀请，已刷新成最新内容',
  inviteCancelledStale: '采购已取消这次邀请',
  receiveQtyInvalid: '实收须为 0 或正整数',
  receiveChanged: '采购修改了这张单，已刷新成最新内容，请核对后再确认',
  poPaidLocked: '已付款，不能再退货或改单价',
  poAllReturned: '已全部退货，不能再退货或改单价',
  paymentAmountStale: (amount: string) => `应付已变为 ${amount}，请核对后再付款`,
  paymentMethodDisabled: '这种付款方式已停用，请换一种',
  materialRequired: '请选择花材',
  materialDuplicate: '同一种花材只能添加一次',
  materialDisabled: '花材不存在或已停用',
  materialNameRequired: '请填写花材名称',
  materialCodeTaken: '编码已被其他花材使用',
  materialStale: '花材刚被修改，已刷新成最新内容',
  supplierStale: '供应商刚被修改，已刷新成最新内容',
  poStale: '采购单刚被修改，已刷新成最新内容',
  poStateLocked: '采购单已收货、拒收或取消，不能再修改',
  receiveCancelled: '采购已取消这张单',
  receiveReason: '改了单价，请填写改价原因',
  repriceReason: '请填写改价原因',
  returnQtyInvalid: '退货量须为大于 0 的整数',
  returnOver: (name: string, qty: number, unit: string) => `${name}最多可退 ${qty} ${unit}`,
  returnStock: (name: string, qty: number, unit: string) =>
    `${name}库存只有 ${qty} ${unit}，不能退`,
  paidBeforeLocked: '付过款，不能再退货或改单价',
  inviteQtyInvalid: '需求量须为大于 0 的整数',
  supplyQtyInvalid: '供货量须为大于 0 的整数，不供的花材请删掉这一行',
  inviteStateLocked: (status: string) => `邀请已是「${status}」，不能再修改`,
  inviteAutoSupplier: '停用供应商，自动取消',
  inviteAutoAccount: '关闭供应商端账号，自动取消',
  inviteShareTitle: '花众采购邀请你填报供货',
  inviteLinkInvalid: '邀请链接无效',
  inviteLinkExpired: '这次邀请已提交或已取消，链接已失效',
  noPayment: '无需付款',
  paymentAlready: '这张单已经付款',
  paymentStale: '这笔付款刚被作废，已刷新成最新内容',
  inviteNotYours: '这张邀请不是发给你的',
  inviteNotFound: '没有这次填报',
  poReturnPaid: '这张单付过款，不能再退货',
  poRepricePaid: '这张单付过款，不能再改单价',
  poReceived: '这张采购单已经收货或拒收',
  poLinesChanged: '采购单明细已变化，请刷新后重试',
  repriceNotice: '这张单改过价，请核对改价记录',
  materialCodeRequired: '请填写花材编码',
  poSupplierChanged: (from: string, to: string) => `供应商 ${from} → ${to}`,
} as const
