import { financeCopy } from './copy-finance.ts'
import { financeCopy as methodCopy } from './copy-screen.ts'
export const statementCopy = {
  ownerOnly: '这张单由其他人经办，请找管理员',
  creditLow: '多收 / 多付余额不足，请刷新后核对',
  voidedShare: '已作废对账单不能分享',
  receivableTodo: '待收款',
  overdueTodo: '逾期未收',
  payableTodo: '待付款',
  refundFirst: '请先作废这笔的退回',
  methodDisabled: methodCopy.methodDisabled,
  statementStale: '对账单状态有变化，请刷新后核对',
  discountOver: '优惠不能超过所勾对账单合计',
  fundStale: '收付款状态有变化，请刷新后核对',
  voidFundBlocked: '不能作废收付款',
  refundStale: '退回记录有变化，请刷新后核对',
  receivedLocked: '已收过款，不能作废',
  creditUsed: '多收 / 多付已使用，请先作废后续单据',
  termRange: '账期天数超出日期范围',
  partyStale: '往来金额有变化，请刷新后核对',
  sourceStale: '来源单据有变化，请刷新后核对',
  sourceRequired: '请选择需要对账的单据',
  duplicateSource: '不能重复选择单据',
  duplicateStatement: '不能重复选择对账单',
  voidReasonRequired: '请填写作废原因',
  voidStatementBlocked: '不能作废对账单',
  termsStale: '往来设置刚被修改，请刷新后核对',
  openingLocked: '已经开过对账单，不能修改期初欠款',
  noChanges: '没有修改内容',
  receiptDetail: '收款',
  paymentDetail: '付款',
  editTerms: '修改往来设置',
  credited: financeCopy.credited,
  supplierCredited: financeCopy.supplierCredited,
  refund: financeCopy.refund,
  registerReceipt: financeCopy.registerReceipt,
  registerPayment: financeCopy.registerPayment,
  voidReceipt: financeCopy.voidReceipt,
  voidPayment: financeCopy.voidPayment,
  refundCredit: financeCopy.refundCredit,
  refundSupplierCredit: financeCopy.refundSupplierCredit,
  voidRefund: financeCopy.voidRefund,
  statement: financeCopy.statement,
  statementCreate: financeCopy.statementCreate,
  statementVoid: financeCopy.statementVoid,
  terms: financeCopy.terms,
  notSet: financeCopy.notSet,
  sourceLocked: (no: string) => `已进对账单 ${no}，请先由财务作废对账单`,
  creditLocked: (kind: 'receipt' | 'payment', no: string) =>
    `这笔${kind === 'receipt' ? '多收' : '多付'}已抵进 ${no}，请先作废那张对账单`,
  dateFuture: (field: string) =>
    `${field === 'receiptDate' ? '收款' : field === 'payDate' ? '付款' : '退回'}日期不能晚于今天`,
}
