// 对账单和往来账的界面文案；页面、日志和校验共用。
export const financeCopy = {
  statement: '对账单',
  statements: '对账单',
  statementDetail: '对账单详情',
  statementCreate: '新建对账单',
  statementShare: '分享对账单',
  statementGenerate: '生成对账单',
  statementVoid: '作废对账单',
  statementDate: '开单日期',
  dueDate: '付款截止',
  period: '对账期间',
  periodFrom: '期间开始',
  periodTo: '期间结束',
  settledDate: '结清日期',
  statementNo: '对账单',
  sourceNo: '单号',
  status: '状态',
  createdBy: '开单人',
  registeredBy: '登记人',
  registeredAt: '登记时间',
  generatedAt: '生成时间',
  customer: '客户',
  supplier: '供应商',
  store: '门店',
  amount: '金额',
  receiptAmount: '收款金额',
  paymentAmount: '付款金额',
  receiptDate: '收款日期',
  paymentDate: '付款日期',
  method: '方式',
  receiptMethod: '收款方式',
  paymentMethod: '付款方式',
  note: '备注',
  no: '单号',
  shipDate: '发货日期',
  afterDate: '处理日期',
  receiveDate: '收货日期',
  stockInDate: '入库日期',
  shipped: '发货金额',
  received: '收货金额',
  after: '售后金额',
  returned: '退货金额',
  discount: '优惠金额',
  discountReason: '优惠原因',
  discountReasonRequired: '请填写优惠原因',
  amountRequired: '请填写金额',
  methodRequired: '请选择收付款方式',
  paid: '已付',
  receivedFund: '已收',
  receipts: '收款记录',
  payments: '付款记录',
  receiptDetail: '收款详情',
  paymentDetail: '付款详情',
  registerReceipt: '登记收款',
  registerPayment: '登记付款',
  confirmReceipt: '确认收款',
  confirmPayment: '确认付款',
  voidReceipt: '作废收款',
  voidPayment: '作废付款',
  voidReason: '作废原因',
  voidedBy: '作废人',
  voidedAt: '作废时间',
  confirmVoid: '确认作废',
  unsettled: '未结清',
  settled: '已结清',
  voided: '已作废',
  unstatemented: '未对账',
  outstanding: '未收',
  payableOutstanding: '待付',
  receivable: '应收',
  payable: '应付',
  storeAmount: '本店金额',
  credited: '多收',
  supplierCredited: '多付',
  deducted: '抵扣多收',
  supplierDeducted: '抵扣多付',
  refund: '退回',
  refundCredit: '多收退回',
  refundSupplierCredit: '多付退回',
  refundDate: '退款日期',
  refundAmount: '退款金额',
  refundMethod: '退款方式',
  confirmRefund: '确认退回',
  refunds: '退回记录',
  voidRefund: '作废退回',
  lastStatementTo: '对账截止',
  lastReceiptDate: '最近收款',
  lastPaymentDate: '最近付款',
  neverStatemented: '未对过账',
  previousPeriod: '上期未对账',
  terms: '往来设置',
  termDays: '账期',
  openingDebt: '期初欠款',
  saveTerms: '保存设置',
  openingLocked: '已经开过对账单，期初欠款不能修改',
  modify: '修改',
  optional: '选填',
  noAfter: '没有售后',
  noReceipt: '还没有收款',
  noPayment: '还没有付款',
  noUnstatemented: '暂无未对账单据',
  noStatements: '暂无对账单',
  noLinkedStatements: '未关联对账单',
  share: '分享',
  imageGenerateFailed: '生成图片失败，请重试',
  imageSaveFailed: '保存图片失败，请重试',
  imageShareFailed: '发送图片未完成，请重试',
  saveImage: '保存图片',
  sendImage: '发给微信好友',
  all: '全部',
  hasOutstanding: '有未收',
  hasPayable: '有待付',
  hasOverdue: '有逾期',
  cancel: '返回',
  saveChanges: '保存修改',
  confirm: '确定',
  review: '重新核对',
  staleReview: '对账单或往来余额有变化，请核对后再确认',
  discountWithoutStatement: '未勾选对账单时不能填写优惠',
  noSources: '请至少选择一张未对账单据',
  sourceChanged: '来源单据有变化，请核对后再生成',
  notSet: '未设置',
  notFilled: '未填',
  currency: '元',
  days: '天',
  qty: '数量',
  unit: '单位',
  code: '编码',
  afterQty: '售后数量',
  imagesRequired: '图片（必填）',
  storeAfterHint: '申请售后请从已发货订单详情进入',
  clearSelected: '清空已选产品吗？',
  overdue: (days: number) => `逾期 ${days} 天`,
  overdueAmount: (amount: string) => `逾期 ${amount}`,
  unsettledCount: (count: number) => `未结清 ${count} 张`,
  sourceCount: (count: number, supplier: boolean) =>
    `${supplier ? '采购单' : '发货单'} ${count} 张`,
  insufficient: (amount: string) => `还差 ${amount}，填优惠或少勾一张`,
  maxRefund: (amount: string) => `最多可退 ${amount}`,
  statementSummary: (no: string, count: number) => (count > 1 ? `${no} 等 ${count} 张` : no),
} as const

// 微信Page.data仅接收可序列化文案，金额/数量函数保留在事件代码里调用。
type FinanceTextKeys = {
  [K in keyof typeof financeCopy]: (typeof financeCopy)[K] extends string ? K : never
}[keyof typeof financeCopy]
export const financeTexts = Object.fromEntries(
  Object.entries(financeCopy).filter(([, value]) => typeof value === 'string'),
) as Pick<typeof financeCopy, FinanceTextKeys>
