// 阶段 5 仓库：手工入库、手工出库、报损、盘点、出库分类、出入库记录的接口报错和日志文案
// （03 章第 8.3 节、05 章第 9 节、06 章 W4–W15）
export const stockCopy = {
  unitInUse: '这项花材已有库存、业务记录或配方引用，不能改单位，请新建花材',
  voidAfterStocktake: '这张单的库存已被后续盘点确认，不能作废，请按实际情况登记新的出入库',
  supplierRequired: '请选择供应商',
  supplierDisabled: '这家供应商已停用，请重新选择',
  outCategoryRequired: '请选择出库分类',
  outCategoryDisabled: '这个出库分类已停用，请重新选择',
  lossReasonRequired: '请填写报损原因',
  qtyInvalid: '数量须为大于 0 的整数',
  linesRequired: '请添加花材',
  priceRequired: '请填写单价，赠送的花材填 0',
  materialDisabled: (name: string) => `${name}已停用，不能入库`,
  stockShort: (name: string, qty: number, unit: string, verb: string) =>
    `${name}库存只有 ${qty} ${unit}，不能${verb}`,
  verbOut: '出库',
  verbLoss: '报损',
  voidStockShort: '库存不够，不能作废',
  voided: '已作废',
  voidedNoReprice: '已作废，不能再改单价',
  notCreator: '只有录这张单的人能作废',
  docStale: '单据已变化，已刷新成最新内容',
  linesChanged: '入库单明细已变化，请刷新后重试',
  imagesTooMany: (max: number) => `最多上传 ${max} 张图片`,
  // 盘点
  categoriesRequired: '请选择分类',
  actualQtyInvalid: '实盘数须为不小于 0 的整数',
  diffReasonRequired: '有差异时请填写差异原因',
  stocktakeStale: '库存已变化，已刷新账面数，请核对后再确认',
  stocktakeLinesChanged: '所选分类的花材有变化，已刷新，请核对后再确认',
  // 出库分类
  categoryNameRequired: '请填写分类名称',
  categoryNameTaken: '已有同名的出库分类',
  keepOneEnabled: '至少保留一个启用的出库分类',
  // 详情、卡片
  batchLabel: (date: string) => `${date} 入库`,
  actualQtyLabel: (unit: string) => `实盘数（${unit}）`,
  diffCount: (count: number) => `有差异 ${count} 项`,
  lineCount: (count: number) => `${count} 种花材`,
  available: (qty: string) => `库存 ${qty}`,
  supplierStockIn: '花众仓库手工入库',
  screen: {
    titles: {
      in: '手工入库单',
      out: '手工出库单',
      loss: '报损',
      stocktakes: '盘点',
      moves: '出入库记录',
      categories: '出库分类',
    },
    create: { in: '新建入库', out: '新建出库', loss: '新建报损', stocktake: '新建盘点' },
    submit: { in: '确认入库', out: '确认出库', loss: '确认报损', stocktake: '确认盘点' },
    empty: {
      in: '入库单',
      out: '出库单',
      loss: '报损记录',
      stocktake: '盘点记录',
      moves: '出入库记录',
    },
    date: { in: '入库日期', out: '出库日期', loss: '报损日期' },
    detail: '单据详情',
    stocktakeDetail: '盘点详情',
    stocktakeForm: '盘点表单',
    selectCategories: '选择花材分类',
    noPickMaterial: '暂无可添加花材',
    startStocktake: '开始盘点',
    outCategory: '出库分类',
    bookQty: '账面数',
    actualQty: '实盘数',
    difference: '差异',
    diffReason: '差异原因',
    noDifference: '无差异',
    amount: '入库金额',
    actor: '经办人',
    reason: '原因（选填）',
    lossReason: '报损原因',
    images: '图片（选填）',
    recordType: '流水类型',
    categories: '花材分类',
    stockIn: '手工入库',
    paymentStockIn: '仓库手工入库',
    stockOut: '手工出库',
    void: '作废单据',
    refreshStock: '库存有变化，请核对后再确认',
    priceChanges: '改价记录',
    supplierHint: '入库单详情',
  },
  // 日志
  log: {
    kindStockIn: '手工入库单',
    kindStockOut: '手工出库单',
    kindLoss: '报损单',
    kindStocktake: '盘点',
    kindOutCategory: '出库分类',
    stockIn: '手工入库',
    stockOut: '手工出库',
    loss: '报损',
    voidStockIn: '作废入库单',
    voidStockOut: '作废出库单',
    voidLoss: '作废报损单',
    reprice: '改单价',
    stocktake: '确认调整',
    createOutCategory: '新增出库分类',
    updateOutCategory: '修改出库分类',
  },
} as const
