export const reworkCopy = {
  afterImageRequired: '请上传售后图片',
  reasonRequired: '请填写原因',
  materialDuplicate: '同一花材只能出现一次',
  voidReasonRequired: '请填写作废原因',
  refundDateRequired: '请选择退款日期',
  requestCancel: '申请取消',
  withdrawCancel: '撤回取消申请',
  approveCancel: '同意取消',
  rejectCancel: '拒绝取消',
  cancelRequest: '取消申请',
  cancelRequests: '取消申请记录',
  cancelReason: '取消原因',
  rejectReason: '拒绝原因',
  voidOrder: '作废订单',
  voidPurchaseOrder: '作废采购单',
  voidedBy: '作废人',
  orderOperationLocked: '当前状态不能进行此操作',
  orderOperationStale: '订单状态或取消申请已变化，请刷新后重试',
  poVoidLocked: '当前状态不能作废采购单',
  poStale: '采购单已变化，请刷新后重试',
  cancelRequestReason: (reason: string) =>
    reason.trim() ? `门店申请取消：${reason.trim()}` : '门店申请取消',
  overShipped: '多发',
  shipDifference: '发货差异',
  refundHistory: '退款历史',
  registerRefund: '登记退款',
  voidRefund: '作废退款',
  refundDate: '退款日期',
  refundAmount: '退款金额',
  refundMethod: '退款方式',
  refundNote: '退款备注',
  refundAmountRequired: '请填写大于 0 的退款金额',
  refundMethodRequired: '请选择退款方式',
  refundConfirm: '确认登记退回？',
  receiptDetail: '收款详情',
  paymentDetail: '付款详情',
  recheck: '重新核对',
  orderReviewed: '已刷新订单与价格，数量和备注已保留，请核对后再确认',
  keepDraft: '保留草稿',
  reviewBeforeSubmit: '提交前核对',
  continueSubmit: '继续提交',
  backToReview: '返回核对',
  allowOverGap: '允许超过当前缺口，请核对数量后继续',
  demandChanged: '需求已变化，请重新核对；当前填写内容已保留',
  noDemand: '当前没有采购需求',
  inTransitSources: '在途来源',
  copyCatalog: '复制目录',
  copySource: '复制来源',
  copyPreview: '复制预览',
  copyConfirm: '确认复制',
  copyRePreview: '重新预览',
  noCopyableCatalog: '没有可复制的目录项',
  refundOver: '退款金额超过多收 / 多付余额',
  refundDateFuture: '退款日期不能晚于今天',
  paymentVoidLocked: '有有效退款，请先作废退款再作废付款',
  receiptVoidLocked: '有有效退款，请先作废退款再作废收款',
  paymentStale: '付款已变化，请刷新后重试',
  refundVoidLocked: '退款已作废',
  refundStale: '退款已变化，请刷新后重试',
  catalogCopySame: '不能复制到同一客户',
  catalogCopyStale: '来源或当前客户的目录已变化，已刷新，请重新勾选',
  catalogCopySkipped: '勾选的产品里有重名或已停用的，不能复制',
  reviewStale: '供应商、花材或需求已变化，请重新核对',
  pendingInviteWarning: '已有待填报邀请，请核对后继续',
  gapChangedWarning: '缺口已变化，请复核；仍可按所填数量提交',
  inTransitNote: '在途不代表已到库',
  noShortage: '当前区间没有缺货花材',
  showAllMaterials: '显示全部花材',
  shortageOnly: '只看缺货',
  viewDocumentHistory: '查看单据及变更记录',
  copyReuseNote: '目标空分类按名称复用，不覆盖现有目录项',
  cancelPending: '取消申请中',
  submitCancelRequest: '提交申请',
  confirmWithdrawCancel: '确认撤回',
  cancelRequestReasonLabel: '申请原因',
  cancelRequestedAt: '申请时间',
  cancelHandledAt: '处理时间',
  paymentInfo: '付款信息',
  paymentAmount: '付款金额',
  copySkipped: (count: number) => `跳过 ${count} 个目录项`,
  copySummary: (count: number) => `将复制 ${count} 个目录项`,
  overdueSummary: (count: number) => `${count} 张订单出货日期已过期，请先处理`,
} as const
export const recordsCopy = {
  time: {
    orderChange: '修改时间',
    poChange: '修改时间',
    priceChange: '改价时间',
    returns: '退货时间',
  },
  actor: '操作人',
  orderChange: '变更记录',
  poChange: '变更记录',
  priceChange: '改价记录',
  returns: '退货记录',
  reason: (text: string) => `原因：${text}`,
  // 默认收起：「变更记录 3 条 ›」，点开展开
  count: (count: number) => `${count} 条`,
} as const
